## All
GET http://localhost:3000/api/employees

### ByID
GET http://localhost:3000/api/employees/22


### 
POST http://localhost:3000/api/employees
Content-Type: application/json

{
    "name": "Rafaela",
    "surname": "Benitez",
    "address": "Conchinchina nº 128",
    "email": "rafaela@gmail.com",
    "phone": "8981444333334",
    "notes": "This is a note parrales"
}

###
PUT http://localhost:3000/api/employees/21
Content-Type: application/json

{
    "name": "MPepopa José",
    "surname": "Peralda",
    "address": "Conchinchina nº 128",
    "email": "parraless@gmail.com",
    "phone": "898144440124",
    "notes": "This is a note parrales"
}

###
DELETE http://localhost:3000/api/employees/22

###
PATCH http://localhost:3000/api/employees/22
Content-Type: application/json

{
    "surname": "Olmos"
}

### Create user example
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "María Luisa",
    "username": "Mlusia",
    "email": "Mlusia@gmail.com",
    "password": "654321"
}

### Get all users
GET http://localhost:3000/api/user

### Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "Mlusia@gmail.com",
  "password": "654321"
}